export const config ={
    clubs:{
        select:[
            {key:'white-company' , value:'White Company', flag:'gb', text:'White Company'},
            {key:'uk-federation' , value:'UK Federation', flag:'gb', text:'UK Federation'}
        ]
    },
    select:{
        categories:[
            { key:'Bohurt', value:'Bohurt',text:'Bohurt'},
            { key:'10v10', value:'10v10',text:'10v10'},
            { key:'16v16', value:'16v16',text:'16v16'},
            { key:'21v21', value:'21v21',text:'21v21'},
            { key:'Sword&Shield', value:'Sword&Shield',text:'Sword&Shield'},
            { key:'Sword&Buckler', value:'Sword&Buckler',text:'Sword&Buckler'},
            { key:'Polearm', value:'Polearm',text:'Polearm'},
            { key:'Longsword', value:'Longsword',text:'Longsword'},
            { key:'Triathlon', value:'Triathlon',text:'Triathlon'},
            { key:'Profight', value:'Profight',text:'Profight'}
        ],
        places:[
            { key:'1st', value:'1st',text:'1st'},
            { key:'2nd', value:'2nd',text:'2nd'},
            { key:'3rd', value:'3rd',text:'3rd'}
        ],
        locations:[
            { name: 'Albania', countryCode: 'al' },
            { name: 'Algeria', countryCode: 'dz' },
            { name: 'Argentina', countryCode: 'ar' },
            { name: 'Armenia', countryCode: 'am' },
            { name: 'Australia', countryCode: 'au' },
            { name: 'Austria', countryCode: 'at' },
            { name: 'Belarus', countryCode: 'by' },
            { name: 'Belgium', countryCode: 'be' },
            { name: 'Bosnia', countryCode: 'ba' },
            { name: 'Botswana', countryCode: 'bw' },
            { name: 'Brazil', countryCode: 'br' },
            { name: 'British Virgin Islands', countryCode: 'vg' },
            { name: 'Brunei', countryCode: 'bn' },
            { name: 'Canada', countryCode: 'ca' },
            { name: 'China', countryCode: 'cn' },
            { name: 'Croatia', countryCode: 'hr' },
            { name: 'Cyprus', countryCode: 'cy' },
            { name: 'Czech Republic', countryCode: 'cz' },
            { name: 'Denmark', countryCode: 'dk' },
            { name: 'Egypt', countryCode: 'eg' },
            { name: 'Estonia', countryCode: 'ee' },
            { name: 'Europeanunion', countryCode: 'eu' },
            { name: 'Finland', countryCode: 'fi' },
            { name: 'France', countryCode: 'fr' },
            { name: 'Georgia', countryCode: 'ge' },
            { name: 'Germany', countryCode: 'de' },
            { name: 'Gibraltar', countryCode: 'gi' },
            { name: 'Greece', countryCode: 'gr' },
            { name: 'Greenland', countryCode: 'gl' },
            { name: 'Hungary', countryCode: 'hu' },
            { name: 'Iceland', countryCode: 'is' },
            { name: 'Ireland', countryCode: 'ie' },
            { name: 'Israel', countryCode: 'il' },
            { name: 'Italy', countryCode: 'it' },
            { name: 'Japan', countryCode: 'jp' },
            { name: 'Latvia', countryCode: 'lv' },
            { name: 'Liechtenstein', countryCode: 'li' },
            { name: 'Lithuania', countryCode: 'lt' },
            { name: 'Luxembourg', countryCode: 'lu' },
            { name: 'Macedonia', countryCode: 'mk' },
            { name: 'Malta', countryCode: 'mt' },
            { name: 'Mexico', countryCode: 'mx' },
            { name: 'Moldova', countryCode: 'md' },
            { name: 'Monaco', countryCode: 'mc' },
            { name: 'Montenegro', countryCode: 'me' },
            { name: 'Netherlands', countryCode: 'nl' },
            { name: 'Norway', countryCode: 'no' },
            { name: 'Oman', countryCode: 'om' },
            { name: 'Poland', countryCode: 'pl' },
            { name: 'Portugal', countryCode: 'pt' },
            { name: 'Romania', countryCode: 'ro' },
            { name: 'Russia', countryCode: 'ru' },
            { name: 'Scotland', countryCode: 'gb sct' },
            { name: 'Serbia', countryCode: 'rs' },
            { name: 'Slovakia', countryCode: 'sk' },
            { name: 'Slovenia', countryCode: 'si' },
            { name: 'South Africa', countryCode: 'za' },
            { name: 'Spain', countryCode: 'es' },
            { name: 'Swaziland', countryCode: 'sz' },
            { name: 'Sweden', countryCode: 'se' },
            { name: 'Switzerland', countryCode: 'ch' },
            { name: 'Turkey', countryCode: 'tr' },
            { name: 'Ukraine', countryCode: 'ua' },
            { name: 'United Kingdom', countryCode: 'gb' },
            { name: 'United States', countryCode: 'us', alias: 'America' },
            { name: 'Vatican City', countryCode: 'va' },
            { name: 'Wales', countryCode: 'gb wls' }
        ]
    }


};

